// Flavour lines shown on the loading screen while the game or a route loads.
export const LOADING_TRIVIA: string[] = [
  'Pitch wisely. The cards you pitch now may be the cards you draw later.',
  'Life is a resource. Sometimes taking damage is better than giving up your whole hand to block.',
  'Think about your Arsenal before ending your turn. A good Arsenal can make next turn much stronger.',
  'Your opponent’s hand size matters. Forcing blocks can be as valuable as dealing damage.',
  'Breakpoints matter. Attacks for 4, 7, 10, and other awkward numbers can demand inefficient blocks.',
  'Present difficult decisions, not just damage.',
  'Know your hero’s game plan.',
  'Sometimes stopping your opponent’s best turn is more important than maximizing yours.',
  'Equipment is a resource. Use armor when the tempo or life actually matters.',
  'Check your opponent’s equipment turn 0 to plan your match properly.',
  'Cards in hand are information. What your opponent kept can tell you what they’re planning.',
  'Check whether an effect says “attack” or “attack action card.” They aren’t always the same thing.',
  'On-hit effects create pressure even when the damage is small.',
  'Not every attack needs to be blocked efficiently.',
  'An awkward block for your opponent is often a good attack for you.',
  'Remember what you pitched. Strong players often know what is coming back.',
  'Fatigue is a win condition. Damage isn’t the only way to win.',
  'Every card your opponent blocks with is one less card in theirs.',
  'When both players are low on life, breakpoints become even more important.',
  'Don’t concede just because the board looks bad. Flesh and Blood games can swing quickly.',
  'Check the graveyards. It can tell you what threats are still left in the decks.',
  'Talishar’s game log is your friend. Use it when you’re unsure what just happened.',
  'Hover or inspect unfamiliar cards. Reading the card is still one of the strongest plays.',
  'Use Talishar’s undo carefully. It’s for fixing mistakes, not scouting alternate lines.',
  'Give your opponent time to respond. They may have reactions or instant-speed effects.',
  'Talishar is not a Judge.',
  'Your deck has a second half. Pitch stacking can make it much stronger, or much worse.',
  'Think about what your opponent wants you to block.',
  'Threat density matters. Sometimes saving your disruption for the right turn is stronger than firing it immediately.',
  'Arcane damage requires a different kind of defense. Keep your Arcane Barrier resources in mind.',
  'Sometimes equipment is worth more as one extra point of block.',
  'Winning the die roll doesn’t always mean you should go first.',
  'Going second gives you the first full offensive hand, but your opponent gets setup opportunities.',
  'Use the first turn differently. With no damage carrying over, setup can be extremely valuable.',
  'Your Arsenal is hidden information. Make your opponent respect it.',
  'Representing a reaction can be almost as powerful as having one.',
  'Don’t autopilot your blocks. Ask what your next hand does first.',
  'Good players maximize value. Great players maximize decisions.',
  'Tempo can be worth more than raw damage.',
  'Disruption is strongest when your opponent has something worth disrupting.',
  'A bad hand can still set up a great next turn.',
  'A strong turn doesn’t always need to deal damage.',
  'Your last life point is the only one you can’t spend.',
  'Think about whether you need to block vanilla damage you can afford to take.',
  'Mistakes happen. Learn the interaction and keep playing.',
  'When in doubt, read the card. Then read it again.',
  'The combat chain is a conversation. Make your opponent answer difficult questions.',
  'Good luck, have fun, and remember to be kind with others.',
  'Know which cards in your deck you are happy to pitch early.',
  'Pitch stacking starts on turn one, whether you planned for it or not.',
  'Count cards left in deck when fatigue starts to matter.',
  'Your opponent’s pitch can reveal what their turn is capable of.',
  'Talishar automates the rules, not the strategy.',
  'If something unexpected happens on Talishar, click Report Bug, and share it with us on Discord.',
  'Undo etiquette matters. Communicate before rewinding a meaningful decision.',
  'Losing a Talishar game can still answer the question you queued up to test.',
  'Your opponent is another person. Give them time to think.',
  'Did you know Talishar used to be named Flesh and Blood Online?',
  'No Wizard, No Ranger, No Assassin, No Kassai, No Pummel, No Ice, No Bravo.',
  'That face-down card has been there for four turns. Be afraid.',
  'No, you will not draw your sideboard cards this game.',
  'The matchup was 70-30 until you queued into it.',
  'Your worst matchup is currently searching for a game.',
  'Somewhere, someone is pitching a Command and Conquer.',
  'Somewhere, someone just blocked with a card they absolutely should not have blocked with.',
  'Somewhere, a Kano player is doing math.',
  'Somewhere, a Guardian player is deciding whether 14 damage is enough.',
  'Somewhere, a Ranger player drew a no arrows hand turn 1.',
  'Somewhere, an Assassin player knows more about your deck than you do.',
  'Somewhere, a Runeblade player is counting resources for the third time.',
  'Somewhere, someone just arsenaled a block card.',
  'Judge! “It works like that on Talishar.”',
  'Have you tried blaming Talishar?',
  'Feature or bug? Ask Discord.',
  'Testing a new deck is a great way to discover every bad matchup simultaneously.',
  'Netdecking saves time you can spend misplaying the deck instead.',
  'Brew responsibly.',
  'Cut one card. Add it back ten minutes later.',
  'Sideboarding: remove six cards, add six cards, regret twelve decisions.',
  'The last three sideboard slots are mostly emotional support.',
  '“It’s good into the meta” is how it begins.',
  'Tier lists are temporary. Hero Mastery is forever.',
  'Your pet deck can still win. This message is not legally binding.',
  'If both players complain, the format may be balanced.',
  '50% win rate: perfectly balanced, emotionally devastating.',
  'The tech card works best when your opponent draws it against you.',
  'Did you know you can share replays with your friends?'
];
