export const HEROES_OF_RATHE: { value: string; label: string; young?: boolean }[] = [
  { value: 'WTR001', label: 'Rhinar' },
  { value: 'WTR002', label: 'Rhinar', young: true },
  { value: 'WTR038', label: 'Bravo' },
  { value: 'WTR039', label: 'Bravo', young: true },
  { value: 'WTR076', label: 'Katsu' },
  { value: 'WTR077', label: 'Katsu', young: true },
  { value: 'WTR113', label: 'Dorinthea' },
  { value: 'WTR114', label: 'Dorinthea', young: true },
  { value: 'ARC001', label: 'Dash' },
  { value: 'ARC002', label: 'Dash', young: true },
  { value: 'ARC038', label: 'Azalea' },
  { value: 'ARC039', label: 'Azalea', young: true },
  { value: 'ARC075', label: 'Viserai' },
  { value: 'ARC076', label: 'Viserai', young: true },
  { value: 'ARC113', label: 'Kano' },
  { value: 'ARC114', label: 'Kano', young: true },
  { value: 'CRU002', label: 'Kayo Berserker Runt', young: true },
  { value: 'CRU046', label: 'Ira', young: true },
  { value: 'CRU047', label: 'Benji', young: true },
  { value: 'CRU077', label: 'Kassai', young: true },
  { value: 'CRU097', label: 'Shiyana', young: true },
  { value: 'CRU099', label: 'Data Doll MKII', young: true },
  { value: 'CRU118', label: 'Kavdaen', young: true },
  { value: 'MON001', label: 'Prism' },
  { value: 'MON002', label: 'Prism', young: true },
  { value: 'MON029', label: 'Boltyn' },
  { value: 'MON030', label: 'Boltyn', young: true },
  { value: 'MON119', label: 'Levia' },
  { value: 'MON120', label: 'Levia', young: true },
  { value: 'MON153', label: 'Chane' },
  { value: 'MON154', label: 'Chane', young: true },
  { value: 'ELE001', label: 'Oldhim' },
  { value: 'ELE002', label: 'Oldhim', young: true },
  { value: 'ELE031', label: 'Lexi' },
  { value: 'ELE032', label: 'Lexi', young: true },
  { value: 'ELE062', label: 'Briar' },
  { value: 'ELE063', label: 'Briar', young: true },
  { value: 'UPR001', label: 'Dromai' },
  { value: 'UPR002', label: 'Dromai', young: true },
  { value: 'UPR044', label: 'Fai' },
  { value: 'UPR045', label: 'Fai', young: true },
  { value: 'OUT001', label: 'Uzuri' },
  { value: 'OUT002', label: 'Uzuri', young: true },
  { value: 'OUT003', label: 'Arakni Solitary Confinement', young: true },
  { value: 'OUT091', label: 'Riptide' },
  { value: 'OUT092', label: 'Riptide', young: true },
  { value: 'EVR120', label: 'Iyslander' },
  { value: 'UPR103', label: 'Iyslander', young: true },
  { value: 'DYN113', label: 'Arakni' },
  { value: 'DYN114', label: 'Arakni Huntsman', young: true },
  { value: 'EVR017', label: 'Bravo Star of the Show' },
  { value: 'EVR019', label: 'Valda' },
  { value: 'EVR085', label: 'Genis Wotchuneed', young: true },
  { value: 'DVR001', label: 'Dorinthea Quicksilver Prodigy', young: true },
  { value: 'DYN001', label: 'Emperor', young: true },
  { value: 'DYN025', label: 'Yoji', young: true },
  { value: 'DTD001', label: 'Prism' },
  { value: 'DTD002', label: 'Prism', young: true },
  { value: 'DTD133', label: 'Vynnset' },
  { value: 'DTD134', label: 'Vynnset', young: true },
  { value: 'TCC001', label: 'Teklovossen', young: true },
  { value: 'TCC027', label: 'Brevant', young: true },
  { value: 'TCC049', label: 'Melody', young: true },
  { value: 'EVO001', label: 'Dash I/O' },
  { value: 'EVO002', label: 'Dash I/O', young: true },
  { value: 'EVO004', label: 'Maxx Nitro' },
  { value: 'EVO005', label: 'Maxx Nitro', young: true },
  { value: 'EVO007', label: 'Teklovossen' },
  { value: 'EVO008', label: 'Teklovossen', young: true },
  { value: 'HVY001', label: 'Kayo Armed and Dangerous' },
  { value: 'HVY002', label: 'Kayo', young: true },
  { value: 'HVY045', label: 'Betsy' },
  { value: 'HVY046', label: 'Betsy', young: true },
  { value: 'HVY047', label: 'Victor Goldmane' },
  { value: 'HVY048', label: 'Victor Goldmane', young: true },
  { value: 'HVY090', label: 'Kassai' },
  { value: 'HVY091', label: 'Kassai', young: true },
  { value: 'HVY092', label: 'Olympia' },
  { value: 'HVY093', label: 'Olympia', young: true },
  { value: 'MST001', label: 'Nuu' },
  { value: 'MST002', label: 'Nuu', young: true },
  { value: 'MST025', label: 'Enigma' },
  { value: 'MST026', label: 'Enigma', young: true },
  { value: 'MST046', label: 'Zen' },
  { value: 'MST047', label: 'Zen', young: true },
  { value: 'TER001', label: 'Terra', young: true },
  { value: 'HER117', label: 'Blaze', young: true },
  { value: 'ROS001', label: 'Florian' },
  { value: 'ROS002', label: 'Florian', young: true },
  { value: 'ROS007', label: 'Aurora' },
  { value: 'ROS008', label: 'Aurora', young: true },
  { value: 'ROS013', label: 'Verdance' },
  { value: 'ROS014', label: 'Verdance', young: true },
  { value: 'ROS019', label: 'Oscilio' },
  { value: 'ROS020', label: 'Oscilio', young: true },
  { value: 'AJV001', label: 'Jarl' },
  { value: 'HNT001', label: 'Arakni Marionette' },
  { value: 'HNT002', label: 'Arakni Web of Deceit', young: true },
  { value: 'HNT054', label: 'Cindra' },
  { value: 'HNT055', label: 'Cindra', young: true },
  { value: 'HNT098', label: 'Fang' },
  { value: 'HNT099', label: 'Fang', young: true },
  { value: 'HNT261', label: 'Slippy' },
  { value: 'HER130', label: 'Slippy' },
  { value: 'SEA001', label: 'Puffin' },
  { value: 'SEA002', label: 'Puffin', young: true },
  { value: 'SEA043', label: 'Gravy Bones' },
  { value: 'SEA044', label: 'Gravy Bones', young: true },
  { value: 'SEA082', label: 'Marlynn' },
  { value: 'SEA083', label: 'Marlynn', young: true },
  { value: 'HER123', label: 'Ira' },
  { value: 'MPG001', label: 'Valda' },
  { value: 'MPG002', label: 'Valda', young: true },
  { value: 'HER135', label: 'Valda' },
  { value: 'SEA123', label: 'Scurv', young: true },
  { value: 'SUP001', label: 'Tuffnut' },
  { value: 'SUP002', label: 'Tuffnut', young: true },
  { value: 'SUP009', label: 'Pleiades' },
  { value: 'SUP010', label: 'Pleiades', young: true },
  { value: 'SUP063', label: 'Kayo Underhanded Cheat' },
  { value: 'SUP064', label: 'Kayo Strong-Arm', young: true },
  { value: 'SUP071', label: 'Lyath Goldmane' },
  { value: 'SUP072', label: 'Lyath Goldmane', young: true },
  { value: 'SMP002', label: 'Bravo', young: true },
];

export const CLASS_OF_RATHE: { label: string }[] = [
  { label: 'Assassin' },
  { label: 'Brute' },
  { label: 'Guardian' },
  { label: 'Illusionist' },
  { label: 'Mechanologist' },
  { label: 'Necromancer' },
  { label: 'Ninja' },
  { label: 'Pirate' },
  { label: 'Ranger' },
  { label: 'Runeblade' },
  { label: 'Warrior' },
  { label: 'Wizard' },
];