export const HEROES_OF_RATHE: { value: string; label: string; young?: boolean }[] = [
  { value: 'WTR001', label: 'Rhinar Reckless Rampage' },
  { value: 'WTR002', label: 'Rhinar', young: true },
  { value: 'WTR038', label: 'Bravo Showstopper' },
  { value: 'WTR039', label: 'Bravo', young: true },
  { value: 'WTR076', label: 'Katsu the Wanderer' },
  { value: 'WTR077', label: 'Katsu', young: true },
  { value: 'WTR113', label: 'Dorinthea Ironsong' },
  { value: 'WTR114', label: 'Dorinthea', young: true },
  { value: 'ARC001', label: 'Dash Inventor Extraordinaire' },
  { value: 'ARC002', label: 'Dash', young: true },
  { value: 'ARC038', label: 'Azalea Ace in the Hole' },
  { value: 'ARC039', label: 'Azalea', young: true },
  { value: 'ARC075', label: 'Viserai Rune Blood' },
  { value: 'ARC076', label: 'Viserai', young: true },
  { value: 'ARC113', label: 'Kano Dracai of Aether' },
  { value: 'ARC114', label: 'Kano', young: true },
  { value: 'CRU002', label: 'Kayo Berserker Runt', young: true },
  { value: 'CRU046', label: 'Ira Crimson Haze', young: true },
  { value: 'CRU047', label: 'Benji the Piercing Wind', young: true },
  { value: 'CRU077', label: 'Kassai Cintari Sellsword', young: true },
  { value: 'CRU097', label: 'Shiyana Diamond Gemini', young: true },
  { value: 'CRU099', label: 'Data Doll MKII', young: true },
  { value: 'CRU118', label: 'Kavdaen Trader of Skins', young: true },
  { value: 'MON001', label: 'Prism Sculptor of Arc Light' },
  { value: 'MON002', label: 'Prism', young: true },
  { value: 'MON029', label: 'Ser Boltyn Breaker of Dawn' },
  { value: 'MON030', label: 'Boltyn', young: true },
  { value: 'MON119', label: 'Levia Shadowborn Abomination' },
  { value: 'MON120', label: 'Levia', young: true },
  { value: 'MON153', label: 'Chane Bound by Shadow' },
  { value: 'MON154', label: 'Chane', young: true },
  { value: 'ELE001', label: 'Oldhim Grandfather of Eternity' },
  { value: 'ELE002', label: 'Oldhim', young: true },
  { value: 'ELE031', label: 'Lexi Livewire' },
  { value: 'ELE032', label: 'Lexi', young: true },
  { value: 'ELE062', label: 'Briar Warden of Thorns' },
  { value: 'ELE063', label: 'Briar', young: true },
  { value: 'UPR001', label: 'Dromai Ash Artist' },
  { value: 'UPR002', label: 'Dromai', young: true },
  { value: 'UPR044', label: 'Fai Rising Rebellion' },
  { value: 'UPR045', label: 'Fai', young: true },
  { value: 'OUT001', label: 'Uzuri Switchblade' },
  { value: 'OUT002', label: 'Uzuri', young: true },
  { value: 'OUT003', label: 'Arakni Solitary Confinement', young: true },
  { value: 'OUT091', label: 'Riptide Lurker of the Deep' },
  { value: 'OUT092', label: 'Riptide', young: true },
  { value: 'EVR120', label: 'Iyslander Stormbind' },
  { value: 'UPR103', label: 'Iyslander', young: true },
  { value: 'DYN113', label: 'Arakni Huntsman' },
  { value: 'DYN114', label: 'Arakni', young: true },
  { value: 'EVR017', label: 'Bravo Star of the Show' },
  { value: 'EVR019', label: 'Valda Brightaxe', young:true },
  { value: 'EVR085', label: 'Genis Wotchuneed', young: true },
  { value: 'DVR001', label: 'Dorinthea Quicksilver Prodigy', young: true },
  { value: 'DYN001', label: 'Emperor Dracai of Aesir', young: true },
  { value: 'DYN025', label: 'Yoji Royal Protector', young: true },
  { value: 'DTD001', label: 'Prism Awakener of Sol' },
  { value: 'DTD002', label: 'Prism Advent of Thrones', young: true },
  { value: 'DTD133', label: 'Vynnset Iron Maiden' },
  { value: 'DTD134', label: 'Vynnset', young: true },
  { value: 'TCC001', label: 'Professor Teklovossen', young: true },
  { value: 'TCC027', label: 'Brevant Civic Protector', young: true },
  { value: 'TCC049', label: 'Melody Sing-along', young: true },
  { value: 'EVO001', label: 'Dash I/O' },
  { value: 'EVO002', label: 'Dash Database', young: true },
  { value: 'EVO004', label: 'Maxx The Hype Nitro' },
  { value: 'EVO005', label: 'Maxx Nitro', young: true },
  { value: 'EVO007', label: 'Teklovossen Esteemed Magnate' },
  { value: 'EVO008', label: 'Teklovossen', young: true },
  { value: 'HVY001', label: 'Kayo Armed and Dangerous' },
  { value: 'HVY002', label: 'Kayo', young: true },
  { value: 'HVY045', label: 'Betsy Skin in the Game' },
  { value: 'HVY046', label: 'Betsy', young: true },
  { value: 'HVY047', label: 'Victor Goldmane High and Mighty' },
  { value: 'HVY048', label: 'Victor Goldmane', young: true },
  { value: 'HVY090', label: 'Kassai of the Golden Sand' },
  { value: 'HVY091', label: 'Kassai', young: true },
  { value: 'HVY092', label: 'Olympia Prized Fighter' },
  { value: 'HVY093', label: 'Olympia', young: true },
  { value: 'MST001', label: 'Nuu Alluring Desire' },
  { value: 'MST002', label: 'Nuu', young: true },
  { value: 'MST025', label: 'Enigma Ledger of Ancestry' },
  { value: 'MST026', label: 'Enigma', young: true },
  { value: 'MST046', label: 'Zen Tamer of Purpose' },
  { value: 'MST047', label: 'Zen', young: true },
  { value: 'TER001', label: 'Terra', young: true },
  { value: 'HER117', label: 'Blaze Firemind', young: true },
  { value: 'ROS001', label: 'Florian Rotwood Harbinger' },
  { value: 'ROS002', label: 'Florian', young: true },
  { value: 'ROS007', label: 'Aurora Shooting Star' },
  { value: 'ROS008', label: 'Aurora', young: true },
  { value: 'ROS013', label: 'Verdance Thorn of the Rose' },
  { value: 'ROS014', label: 'Verdance', young: true },
  { value: 'ROS019', label: 'Oscilio Constella Intelligence' },
  { value: 'ROS020', label: 'Oscilio', young: true },
  { value: 'AJV001', label: 'Jarl Vetreidi' },
  { value: 'HNT001', label: 'Arakni Marionette' },
  { value: 'HNT002', label: 'Arakni Web of Deceit', young: true },
  { value: 'HNT054', label: 'Cindra Dracai of Retribution' },
  { value: 'HNT055', label: 'Cindra', young: true },
  { value: 'HNT098', label: 'Fang Dracai of Blades' },
  { value: 'HNT099', label: 'Fang', young: true },
  { value: 'HER130', label: 'Arakni 5L!p3d 7hRu 7h3 cR4X' },
  { value: 'SEA001', label: 'Puffin Hightail' },
  { value: 'SEA002', label: 'Puffin', young: true },
  { value: 'SEA043', label: 'Gravy Bones Shipwrecked Looter' },
  { value: 'SEA044', label: 'Gravy Bones', young: true },
  { value: 'SEA082', label: 'Marlynn Treasure Hunter' },
  { value: 'SEA083', label: 'Marlynn', young: true },
  { value: 'HER123', label: 'Ira Scarlet Revenger' },
  { value: 'MPG001', label: 'Valda Seismic Impact' },
  { value: 'SEA123', label: 'Scurv Stowaway', young: true },
  { value: 'SUP001', label: 'Tuffnut Bumbling Hulkster' },
  { value: 'SUP002', label: 'Tuffnut', young: true },
  { value: 'SUP009', label: 'Pleiades Superstar' },
  { value: 'SUP010', label: 'Pleiades', young: true },
  { value: 'SUP063', label: 'Kayo Underhanded Cheat' },
  { value: 'SUP064', label: 'Kayo Strong-Arm', young: true },
  { value: 'SUP071', label: 'Lyath Goldmane Vile Savant' },
  { value: 'SUP072', label: 'Lyath Goldmane', young: true },
  { value: 'SMP001', label: 'Bolfar Bear Hands', young: true },
  { value: 'SMP002', label: 'Bravo Flattering Showman', young: true },
  { value: 'JDG024', label: 'Brutus Summa Rudis', young:true },
  { value: 'MST238', label: 'Enigma New Moon', young: true },
  { value: 'SMP003', label: 'Fightmaster Kox', young: true },
  { value: 'LSS021', label: 'Frankie Make Ends Meet', young: true },
  { value: 'SMP004', label: 'Groundbreaker Crix', young: true },
  { value: 'AHA001', label: 'Hala Bladesaint of the Vow' },
  { value: 'SMP005', label: 'Reya the Undying', young: true },
  { value: 'LSS001', label: 'Ruudi Gem Keeper', },
  { value: 'HER100', label: 'Squizzy and Floof', young: true },
  { value: 'JDG001', label: 'Taipanis Dracai of Judgement', young: true },
  { value: 'JDG006', label: 'Theryon Magister of Justice', young: true },
];

export const CLASS_OF_RATHE: { label: string }[] = [
  { label: 'Assassin' },
  { label: 'Brute' },
  { label: 'Guardian' },
  { label: 'Illusionist' },
  { label: 'Mechanologist' },
  { label: 'Necromancer' },
  { label: 'Ninja' },
  { label: 'Pirate' },
  { label: 'Ranger' },
  { label: 'Runeblade' },
  { label: 'Warrior' },
  { label: 'Wizard' },
];