export const HEROES_OF_RATHE: { value: string; label: string }[] = [
  { value: 'WTR001', label: 'Rhinar' },
  { value: 'WTR002', label: 'Rhinar' },
  { value: 'WTR038', label: 'Bravo' },
  { value: 'WTR039', label: 'Bravo' },
  { value: 'WTR076', label: 'Katsu' },
  { value: 'WTR077', label: 'Katsu' },
  { value: 'WTR113', label: 'Dorinthea' },
  { value: 'WTR114', label: 'Dorinthea' },
  { value: 'ARC001', label: 'Dash' },
  { value: 'ARC002', label: 'Dash' },
  { value: 'ARC038', label: 'Azalea' },
  { value: 'ARC039', label: 'Azalea' },
  { value: 'ARC075', label: 'Viserai' },
  { value: 'ARC076', label: 'Viserai' },
  { value: 'ARC113', label: 'Kano' },
  { value: 'ARC114', label: 'Kano' },
  { value: 'CRU002', label: 'Kayo' },
  { value: 'CRU046', label: 'Ira' },
  { value: 'CRU047', label: 'Benji' },
  { value: 'CRU077', label: 'Kassai' },
  { value: 'CRU097', label: 'Shiyana' },
  { value: 'CRU099', label: 'Data Doll MKII' },
  { value: 'CRU118', label: 'Kavdaen' },
  { value: 'MON001', label: 'Prism' },
  { value: 'MON002', label: 'Prism' },
  { value: 'MON029', label: 'Boltyn' },
  { value: 'MON030', label: 'Boltyn' },
  { value: 'MON119', label: 'Levia' },
  { value: 'MON120', label: 'Levia' },
  { value: 'MON153', label: 'Chane' },
  { value: 'MON154', label: 'Chane' },
  { value: 'ELE001', label: 'Oldhim' },
  { value: 'ELE002', label: 'Oldhim' },
  { value: 'ELE031', label: 'Lexi' },
  { value: 'ELE032', label: 'Lexi' },
  { value: 'ELE062', label: 'Briar' },
  { value: 'ELE063', label: 'Briar' },
  { value: 'UPR001', label: 'Dromai' },
  { value: 'UPR002', label: 'Dromai' },
  { value: 'UPR044', label: 'Fai' },
  { value: 'UPR045', label: 'Fai' },
  { value: 'OUT001', label: 'Uzuri' },
  { value: 'OUT002', label: 'Uzuri' },
  { value: 'OUT003', label: 'Arakni, Slippy' },
  { value: 'OUT091', label: 'Riptide' },
  { value: 'OUT092', label: 'Riptide' },
  { value: 'UPR102', label: 'Iyslander' },
  { value: 'UPR103', label: 'Iyslander' },
  { value: 'DYN113', label: 'Arakni, Huntsman' },
  { value: 'DYN114', label: 'Arakni, Huntsman' },
  { value: 'EVR017', label: 'Bravo, Star of the Show' },
  { value: 'EVR019', label: 'Valda' },
  { value: 'EVR085', label: 'Genis Wotchuneed' },
  { value: 'DVR001', label: 'Dorinthea' },
  { value: 'DYN001', label: 'Emperor' },
  { value: 'DYN025', label: 'Yoji' },
  { value: 'DTD001', label: 'Prism' },
  { value: 'DTD133', label: 'Vynnset' },
  { value: 'DTD134', label: 'Vynnset' },
  { value: 'TCC001', label: 'Teklovossen' },
  { value: 'TCC027', label: 'Brevant' },
  { value: 'TCC049', label: 'Melody' },
  { value: 'EVO001', label: 'Dash, I/O' },
  { value: 'EVO002', label: 'Dash, I/O' },
  { value: 'EVO004', label: 'Maxx Nitro' },
  { value: 'EVO005', label: 'Maxx Nitro' },
  { value: 'EVO007', label: 'Teklovossen' },
  { value: 'EVO008', label: 'Teklovossen' },
  { value: 'HVY001', label: 'Kayo' },
  { value: 'HVY002', label: 'Kayo' },
  { value: 'HVY045', label: 'Betsy' },
  { value: 'HVY046', label: 'Betsy' },
  { value: 'HVY047', label: 'Victor Goldmane' },
  { value: 'HVY048', label: 'Victor Goldmane' },
  { value: 'HVY090', label: 'Kassai' },
  { value: 'HVY091', label: 'Kassai' },
  { value: 'HVY092', label: 'Olympia' },
  { value: 'HVY093', label: 'Olympia' },
  { value: 'MST001', label: 'Nuu' },
  { value: 'MST002', label: 'Nuu' },
  { value: 'MST025', label: 'Enigma' },
  { value: 'MST026', label: 'Enigma' },
  { value: 'MST046', label: 'Zen' },
  { value: 'MST047', label: 'Zen' },
  { value: 'TER001', label: 'Terra' },
  { value: 'HER117', label: 'Blaze' },
  { value: 'ROS001', label: 'Florian' },
  { value: 'ROS002', label: 'Florian' },
  { value: 'ROS007', label: 'Aurora' },
  { value: 'ROS008', label: 'Aurora' },
  { value: 'ROS013', label: 'Verdance' },
  { value: 'ROS014', label: 'Verdance' },
  { value: 'ROS019', label: 'Oscilio' },
  { value: 'ROS020', label: 'Oscilio' },
  { value: 'AJV001', label: 'Jarl' },
  { value: 'HNT001', label: 'Arakni, Marionette' },
  { value: 'HNT002', label: 'Arakni, Marionette' },
  { value: 'HNT054', label: 'Cindra' },
  { value: 'HNT055', label: 'Cindra' },
  { value: 'HNT098', label: 'Fang' },
  { value: 'HNT099', label: 'Fang' },
  { value: 'HNT261', label: 'Arakni, Slippy' }, //Slippy
  { value: 'HER130', label: 'Arakni, Slippy' }, //Slippy
  { value: 'SEA001', label: 'Puffin' },
  { value: 'SEA002', label: 'Puffin' },
  { value: 'SEA043', label: 'Gravy Bones' },
  { value: 'SEA044', label: 'Gravy Bones' },
  { value: 'SEA082', label: 'Marlynn' },
  { value: 'SEA083', label: 'Marlynn' },
  { value: 'HER123', label: 'Ira' },
  { value: 'MPG001', label: 'Valda' },
  { value: 'MPG002', label: 'Valda' },
  { value: 'HER135', label: 'Valda' },
  { value: 'SEA123', label: 'Scurv' },
  { value: 'SUP001', label: 'Tuffnut' },
  { value: 'SUP002', label: 'Tuffnut' },
  { value: 'SUP009', label: 'Pleiades' },
  { value: 'SUP010', label: 'Pleiades' },
  { value: 'SUP063', label: 'Kayo' },
  { value: 'SUP064', label: 'Kayo' },
  { value: 'SUP071', label: 'Lyath Goldmane' },
  { value: 'SUP072', label: 'Lyath Goldmane' },
];
