export const CARD_BACK = {
  '0': 'CardBack',
  '1': 'CBBlack',
  '2': 'CBCreamWhite',
  '3': 'CBGold',
  '4': 'CBWhite',
  '5': 'CBRed',
  '6': 'CBParchment',
  '7': 'CBBlue',
  '8': 'CBRuneblood',
  '9': 'CBPushThePoint',
  '10': 'CBGoAgainGaming',
  '11': 'CBGAG_AzaleaCult',
  '12': 'CBGAG_Azalea',
  '13': 'CBGAG_AzaleaShot',
  '14': 'CBGAG_Dorinthea',
  '15': 'CBGAG_Dromai',
  '16': 'CBGAG_Kassai',
  '17': 'CBRedZoneRogue',
  '18': 'CBRZR_10k',
  '19': 'CBRZR_KadikosLibrary',
  '20': 'CBRZR_Vehya',
  '21': 'CBFabrary1',
  '22': 'CBFabrary2',
  '23': 'CBManSant',
  '24': 'CBAttackActionPodcast',
  '25': 'CBArsenalPass',
  '26': 'CBTekloFoundry',
  '27': 'CBPummelowanko',
  '28': 'CBDragonShieldProTeamWB',
  '29': 'CBFleshAndCommonBlood',
  '30': 'CBSinOnStream',
  '31': 'CBFreshAndBuds',
  '32': 'CBSloopdoop',
  '33': 'CBDMArmada',
  '35': 'CBTheCardGuyz',
  '36': 'CBHomeTownTCG',
  '37': 'CBAscentGaming',
  '38': 'CBFleshAndPod',
  '39': 'CBKappolo',
  '40': 'CBLibrariansOfSolana',
  '41': 'CBTheMetrixMetagame',
  '42': 'CBEternalOracles',
  '43': 'CBTheTablePit',
  '44': 'CBTCGTed',
  '45': 'CBLuminaris',
  '46': 'CBFaBLab',
  '47': 'CBCardAdvantage',
  '48': 'CBOnHit',
  '49': 'CBSecondCycle',
  '50': 'CBRavenousBabble',
  '51': 'CBBlackWingStudio',
  '52': 'CBManSantBlack',
  '53': 'CBOnHitEffect',
  '54': 'CBDaganWhite',
  '55': 'CBSonicDoom',
  '56': 'CBBrandao',
  '57': 'CBFabrary3',
  '58': 'CBFabrary4',
  '59': 'CBFabrary5',
  '60': 'CBFabrary6',
  '61': 'CBFabrary7',
  '62': 'CBFabrary8',
  '63': 'CBOffTheRailsTCG',
  '64': 'CBPummel',
  '65': 'CBNxi',
  '66': 'CBPvtVoid',
  '67': 'CBEmperorsRome',
  '68': 'CBWeMakeBest',
  '69': 'CBWeMakeBest2',
  '70': 'CBSunflowerSamurai',
  '71': 'CBMnRCast',
  '72': 'CBOnTheBauble',
  '73': 'CBGorganianTome',
  '74': 'CBFABChaos',
  '75': 'CBColdFoilControl',
  '76': 'CBDailyFab',
  '77': 'CBRighteousGaming',
  '78': 'CBRighteousGaming2',
  '79': 'CBThePlagueHive',
  '80': 'CBDropcast',
  '81': 'CBSunflowerSamurai',
  '82': 'CBTalisharTeam',
  '83': 'CBTalisharTeam2',
  '84': 'CBTideBreakers',
  '85': 'CBCD1',
  '86': 'CBCD2',
  '87': 'CBCupofTCG',
  '88': 'CBScowlingFleshBag',
} as { [key: string]: string };

export const PLAYMATS = {
  '0': 'Default',
  '1': 'Demonastery',
  '2': 'Metrix',
  '3': 'Misteria',
  '4': 'The-Pits',
  '5': 'Savage-Lands',
  '6': 'Solana',
  '7': 'Ironsong-Determination',
  '8': 'Volcor',
  '9': 'Data-Doll',
  '10': 'Korshem',
  '11': 'Dynasty',
  '12': 'Everfest',
  '13': 'Find-Center',
  '14': 'Part-The-Mistveil',
  '15': 'Rosetta',
  '16': 'Bare-Fangs-AHS',
  '17': 'Erase-Face-AHS',
  '18': 'Dusk-Till-Dawn-AHS',
  '19': 'Exude-Confidence-AHS',
  '20': 'Command-and-Conquer-AHS',
  '21': 'Swarming-Gloomveil-AHS',
} as { [key: string]: string };

export const PLAYER_PLAYMATS = [
  '0',
  '9',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16'
];
